# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/yudi/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/yudi

PRODUCT_COPY_FILES += \
    vendor/xiaomi/yudi/proprietary/vendor/etc/audio/sku_cape/audio_effects.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/sku_cape/audio_effects.xml \
    vendor/xiaomi/yudi/proprietary/vendor/etc/audio/sku_cape/mixer_paths_overlay_dynamic.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/sku_cape/mixer_paths_overlay_dynamic.xml \
    vendor/xiaomi/yudi/proprietary/vendor/etc/audio/sku_cape/mixer_paths_overlay_static.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/sku_cape/mixer_paths_overlay_static.xml \
    vendor/xiaomi/yudi/proprietary/vendor/etc/audio/sku_cape/mixer_paths_waipio_cdp.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/sku_cape/mixer_paths_waipio_cdp.xml \
    vendor/xiaomi/yudi/proprietary/vendor/etc/audio/sku_cape/mixer_paths_waipio_mtp.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/sku_cape/mixer_paths_waipio_mtp.xml \
    vendor/xiaomi/yudi/proprietary/vendor/etc/audio/sku_cape/mixer_paths_waipio_qrd.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/sku_cape/mixer_paths_waipio_qrd.xml \
    vendor/xiaomi/yudi/proprietary/vendor/etc/audio/sku_cape/resourcemanager_upd.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/sku_cape/resourcemanager_upd.xml \
    vendor/xiaomi/yudi/proprietary/vendor/etc/audio/sku_cape/resourcemanager_waipio_cdp.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/sku_cape/resourcemanager_waipio_cdp.xml \
    vendor/xiaomi/yudi/proprietary/vendor/etc/audio/sku_cape/resourcemanager_waipio_mtp.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/sku_cape/resourcemanager_waipio_mtp.xml \
    vendor/xiaomi/yudi/proprietary/vendor/etc/audio/sku_cape/resourcemanager_waipio_qrd.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/sku_cape/resourcemanager_waipio_qrd.xml \
    vendor/xiaomi/yudi/proprietary/vendor/etc/audio_cloud_control_white_list.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_cloud_control_white_list.xml \
    vendor/xiaomi/yudi/proprietary/vendor/etc/backend_conf.xml:$(TARGET_COPY_OUT_VENDOR)/etc/backend_conf.xml \
    vendor/xiaomi/yudi/proprietary/vendor/etc/bluetooth_qti_hearing_aid_audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/bluetooth_qti_hearing_aid_audio_policy_configuration.xml \
    vendor/xiaomi/yudi/proprietary/vendor/etc/camera/yudi_enhance_motiontuning.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/yudi_enhance_motiontuning.xml \
    vendor/xiaomi/yudi/proprietary/vendor/etc/camera/yudi_motiontuning.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/yudi_motiontuning.xml \
    vendor/xiaomi/yudi/proprietary/vendor/etc/card-defs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/card-defs.xml \
    vendor/xiaomi/yudi/proprietary/vendor/etc/display/qdcm_calib_data_xiaomi_m80_42_02_0a_video_mode_dual_dsi_dphy_panel.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/qdcm_calib_data_xiaomi_m80_42_02_0a_video_mode_dual_dsi_dphy_panel.json \
    vendor/xiaomi/yudi/proprietary/vendor/etc/microphone_characteristics.xml:$(TARGET_COPY_OUT_VENDOR)/etc/microphone_characteristics.xml \
    vendor/xiaomi/yudi/proprietary/vendor/etc/sensors/config/ak991x_dri_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ak991x_dri_0.json \
    vendor/xiaomi/yudi/proprietary/vendor/etc/sensors/config/sm8450_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sm8450_ak991x_0.json \
    vendor/xiaomi/yudi/proprietary/vendor/etc/sensors/config/sm8450_vl53l5_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sm8450_vl53l5_0.json \
    vendor/xiaomi/yudi/proprietary/vendor/etc/sensors/config/sns_collision_detection.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_collision_detection.json \
    vendor/xiaomi/yudi/proprietary/vendor/etc/sensors/config/sns_oem_hall.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_oem_hall.json \
    vendor/xiaomi/yudi/proprietary/vendor/etc/usecaseKvManager.xml:$(TARGET_COPY_OUT_VENDOR)/etc/usecaseKvManager.xml \
    vendor/xiaomi/yudi/proprietary/vendor/firmware/0_click_P_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/0_click_P_RTP.bin \
    vendor/xiaomi/yudi/proprietary/vendor/firmware/1_doubelClick_P_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/1_doubelClick_P_RTP.bin \
    vendor/xiaomi/yudi/proprietary/vendor/firmware/2_tick_P_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/2_tick_P_RTP.bin \
    vendor/xiaomi/yudi/proprietary/vendor/firmware/3_thud_P_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/3_thud_P_RTP.bin \
    vendor/xiaomi/yudi/proprietary/vendor/firmware/4_pop_P_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/4_pop_P_RTP.bin \
    vendor/xiaomi/yudi/proprietary/vendor/firmware/5_heavyClick_P_RTP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/5_heavyClick_P_RTP.bin \
    vendor/xiaomi/yudi/proprietary/vendor/firmware/BLH-cs35l43-dsp1-spk-prot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/BLH-cs35l43-dsp1-spk-prot.bin \
    vendor/xiaomi/yudi/proprietary/vendor/firmware/BLL-cs35l43-dsp1-spk-prot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/BLL-cs35l43-dsp1-spk-prot.bin \
    vendor/xiaomi/yudi/proprietary/vendor/firmware/BRH-cs35l43-dsp1-spk-prot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/BRH-cs35l43-dsp1-spk-prot.bin \
    vendor/xiaomi/yudi/proprietary/vendor/firmware/BRL-cs35l43-dsp1-spk-prot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/BRL-cs35l43-dsp1-spk-prot.bin \
    vendor/xiaomi/yudi/proprietary/vendor/firmware/TLH-cs35l43-dsp1-spk-prot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/TLH-cs35l43-dsp1-spk-prot.bin \
    vendor/xiaomi/yudi/proprietary/vendor/firmware/TLL-cs35l43-dsp1-spk-prot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/TLL-cs35l43-dsp1-spk-prot.bin \
    vendor/xiaomi/yudi/proprietary/vendor/firmware/TRH-cs35l43-dsp1-spk-prot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/TRH-cs35l43-dsp1-spk-prot.bin \
    vendor/xiaomi/yudi/proprietary/vendor/firmware/TRL-cs35l43-dsp1-spk-prot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/TRL-cs35l43-dsp1-spk-prot.bin \
    vendor/xiaomi/yudi/proprietary/vendor/firmware/cs35l43-dsp1-spk-prot.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l43-dsp1-spk-prot.wmfw \
    vendor/xiaomi/yudi/proprietary/vendor/firmware/novatek_nt36532_m80_fw_csot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_nt36532_m80_fw_csot.bin \
    vendor/xiaomi/yudi/proprietary/vendor/firmware/novatek_nt36532_m80_mp_csot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_nt36532_m80_mp_csot.bin \
    vendor/xiaomi/yudi/proprietary/vendor/lib64/camera/com.qti.actuator.yudi_qtech_s5kjn1_gt9764_wide_i_actuator.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.actuator.yudi_qtech_s5kjn1_gt9764_wide_i_actuator.so \
    vendor/xiaomi/yudi/proprietary/vendor/lib64/camera/com.qti.eeprom.yudi_aac_imx596_p24c64f_front_i_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.eeprom.yudi_aac_imx596_p24c64f_front_i_eeprom.so \
    vendor/xiaomi/yudi/proprietary/vendor/lib64/camera/com.qti.eeprom.yudi_ofilm_sc202cs_depth_i_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.eeprom.yudi_ofilm_sc202cs_depth_i_eeprom.so \
    vendor/xiaomi/yudi/proprietary/vendor/lib64/camera/com.qti.eeprom.yudi_qtech_s5kjn1_gt24p128e_wide_i_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.eeprom.yudi_qtech_s5kjn1_gt24p128e_wide_i_eeprom.so \
    vendor/xiaomi/yudi/proprietary/vendor/lib64/camera/com.qti.sensor.yudi_aac_imx596_front_i.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensor.yudi_aac_imx596_front_i.so \
    vendor/xiaomi/yudi/proprietary/vendor/lib64/camera/com.qti.sensor.yudi_ofilm_sc202cs_depth_i.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensor.yudi_ofilm_sc202cs_depth_i.so \
    vendor/xiaomi/yudi/proprietary/vendor/lib64/camera/com.qti.sensor.yudi_qtech_s5kjn1_wide_i.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensor.yudi_qtech_s5kjn1_wide_i.so \
    vendor/xiaomi/yudi/proprietary/vendor/lib64/camera/com.qti.sensormodule.yudi_aac_imx596_front_i.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.yudi_aac_imx596_front_i.bin \
    vendor/xiaomi/yudi/proprietary/vendor/lib64/camera/com.qti.sensormodule.yudi_ofilm_sc202cs_depth_i.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.yudi_ofilm_sc202cs_depth_i.bin \
    vendor/xiaomi/yudi/proprietary/vendor/lib64/camera/com.qti.sensormodule.yudi_qtech_s5kjn1_wide_i.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.yudi_qtech_s5kjn1_wide_i.bin \
    vendor/xiaomi/yudi/proprietary/vendor/lib64/camera/com.qti.tuned.default.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.default.bin \
    vendor/xiaomi/yudi/proprietary/vendor/lib64/camera/com.qti.tuned.yudi_aac_imx596_front.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.yudi_aac_imx596_front.bin \
    vendor/xiaomi/yudi/proprietary/vendor/lib64/camera/com.qti.tuned.yudi_ofilm_sc202cs_depth.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.yudi_ofilm_sc202cs_depth.bin \
    vendor/xiaomi/yudi/proprietary/vendor/lib64/camera/com.qti.tuned.yudi_qtech_s5kjn1_wide.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.yudi_qtech_s5kjn1_wide.bin \
    vendor/xiaomi/yudi/proprietary/vendor/lib64/hw/fingerprint.goodix.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/fingerprint.goodix.so \
    vendor/xiaomi/yudi/proprietary/vendor/lib64/libSnpeHtpV73Stub.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libSnpeHtpV73Stub.so \
    vendor/xiaomi/yudi/proprietary/vendor/lib64/libgf_ca.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libgf_ca.so \
    vendor/xiaomi/yudi/proprietary/vendor/lib64/libgf_hal.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libgf_hal.so \
    vendor/xiaomi/yudi/proprietary/vendor/lib64/libgoodixhwfingerprint.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libgoodixhwfingerprint.so \
    vendor/xiaomi/yudi/proprietary/vendor/lib64/libhta_hexagon_runtime_snpe.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libhta_hexagon_runtime_snpe.so \
    vendor/xiaomi/yudi/proprietary/vendor/lib64/vendor.xiaomi.hardware.fingerprintextension@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.xiaomi.hardware.fingerprintextension@1.0.so \
    vendor/xiaomi/yudi/proprietary/vendor/lib64/vendor.xiaomi.hardware.fx.tunnel@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.xiaomi.hardware.fx.tunnel@1.0.so
